LevelResourcePointers:
    dw Level0
    dw Level1
    dw Level2
    dw Level3
    dw Level4
    dw Level5
    dw Level6
    dw Level7
    dw Level8
    dw Level9
    dw LevelA
    dw LevelB
    dw LevelC
    dw LevelD
    dw LevelE
    dw LevelF
    dw Level10
    dw Level11
    dw Level12
    dw Level13
    dw Level14
    dw Level15
    dw Level16
    dw Level17
    dw Level18
    dw Level19
    dw Level1A
    dw Level1B
    dw Level1C
    dw Level1D
    dw Level1E
    dw Level1F
    dw Level20
    dw Level21
    dw Level22
    dw Level23
    dw Level24
    dw Level25
    dw Level26
    dw Level27
    dw Level28
    dw Level29
    dw Level2A
    dw Level2B
    dw Level2C
    dw Level2D
    dw Level2E
    dw Level2F
    dw Level30
    dw Level31
    dw Level32
    dw Level33
    dw Level34
    dw Level35
    dw Level36
    dw Level37
    dw Level38
    dw Level39
    dw Level3A
    dw Level3B
    dw Level3C
    dw Level3D
    dw Level3E
    dw Level3F
    dw Level40
    dw Level41
    dw Level42
    dw Level43
    dw Level44
    dw Level45
    dw Level46
    dw Level47
    dw Level48
    dw Level49
    dw Level4A
    dw Level4B
    dw Level4C
    dw Level4D
    dw Level4E
    dw Level4F
    dw Level50
    dw Level51
    dw Level52
    dw Level53
    dw Level54
    dw Level55
    dw Level56
    dw Level57
    dw Level58
    dw Level59
    dw Level5A
    dw Level5B
    dw Level5C
    dw Level5D
    dw Level5E
    dw Level5F
    dw Level60
    dw Level61
    dw Level62
    dw Level63
    dw Level64
    dw Level65
    dw Level66
    dw Level67
    dw Level68
    dw Level69
    dw Level6A
    dw Level6B
    dw Level6C
    dw Level6D
    dw Level6E
    dw Level6F
    dw Level70
    dw Level71
    dw Level72
    dw Level73
    dw Level74
    dw Level75
    dw Level76
    dw Level77
    dw Level78
    dw Level79
    dw Level7A
    dw Level7B
    dw Level7C
    dw Level7D
    dw Level7E
    dw Level7F
    dw Level80
    dw Level81
    dw Level82
    dw Level83
    dw Level84
    dw Level85
    dw Level86
    dw Level87
    dw Level88
    dw Level89
    dw Level8A
    dw Level8B
    dw Level8C
    dw Level8D
    dw Level8E
    dw Level8F
    dw Level90
    dw Level91
    dw Level92
    dw Level93
    dw Level94
    dw Level95
    dw Level96
    dw Level97
    dw Level98
    dw Level99
    dw Level9A
    dw Level9B
    dw Level9C
    dw Level9D
    dw Level9E
    dw Level9F
    dw LevelA0
    dw LevelA1
    dw LevelA2
    dw LevelA3
    dw LevelA4
    dw LevelA5
    dw LevelA6
    dw LevelA7
    dw LevelA8
    dw LevelA9
    dw LevelAA
    dw LevelAB
    dw LevelAC
    dw LevelAD
    dw LevelAE
    dw LevelAF
    dw LevelB0
    dw LevelB1
    dw LevelB2
    dw LevelB3
    dw LevelB4
    dw LevelB5
    dw LevelB6
    dw LevelB7
    dw LevelB8
    dw LevelB9
    dw LevelBA
    dw LevelBB
    dw LevelBC
    dw LevelBD
    dw LevelBE
    dw LevelBF
    dw LevelC0
    dw LevelC1
    dw LevelC2
    dw LevelC3
    dw LevelC4
    dw LevelC5
    dw LevelC6
    dw LevelC7
    dw LevelC8
    dw LevelC9
    dw LevelCA
    dw LevelCB
    dw LevelCC
    dw LevelCD
    dw LevelCE
    dw LevelCF
    dw LevelD0
    dw LevelD1
    dw LevelD2
    dw LevelD3
    dw LevelD4
    dw LevelD5
    dw LevelD6
    dw LevelD7
    dw LevelD8
    dw LevelD9
    dw LevelDA
    dw LevelDB
    dw LevelDC
    dw LevelDD
    dw LevelDE
    dw LevelDF
    dw LevelE0
    dw LevelE1
    dw LevelE2
    dw LevelE3
    dw LevelE4
    dw LevelE5
    dw LevelE6
    dw LevelE7
    dw LevelE8
    dw LevelE9
    dw LevelEA
    dw LevelEB
    dw LevelEC
    dw LevelED
    dw LevelEE
    dw LevelEF
    dw LevelF0
    dw LevelF1
    dw LevelF2
    dw LevelF3
    dw LevelF4
    dw LevelF5
    dw LevelF6
    dw LevelF7
    dw LevelF8
    dw LevelF9
    dw LevelFA
    dw LevelFB
    dw LevelFC
    dw LevelFD
    dw LevelFE
    dw LevelFF
    dw Level100
    dw Level101
    dw Level102
    dw Level103
    dw Level104
    dw Level105
    dw Level106
    dw Level107
    dw Level108
    dw Level109
    dw Level10A
    dw Level10B
    dw Level10C
    dw Level10D
    dw Level10E
    dw Level10F
    dw Level110
    dw Level111
    dw Level112
    dw Level113
    dw Level114
    dw Level115
    dw Level116
    dw Level117
    dw Level118
    dw Level119
    dw Level11A
    dw Level11B
    dw Level11C
    dw Level11D
    dw Level11E
    dw Level11F
    dw Level120
    dw Level121
    dw Level122
    dw Level123
    dw Level124
    dw Level125
    dw Level126
    dw Level127
    dw Level128
    dw Level129
    dw Level12A
    dw Level12B
    dw Level12C
    dw Level12D
    dw Level12E
    dw Level12F
    dw Level130
    dw Level131
    dw Level132
    dw Level133
    dw Level134
    dw Level135
    dw Level136
    dw Level137
    dw Level138
    dw Level139
    dw Level13A
    dw Level13B
    dw Level13C
    dw Level13D
    dw Level13E
    dw Level13F
    dw Level140
    dw Level141
    dw Level142
    dw Level143
    dw Level144
    dw Level145
    dw Level146
    dw Level147
    dw Level148
    dw Level149
    dw Level14A
    dw Level14B
    dw Level14C
    dw Level14D
    dw Level14E
    dw Level14F
    dw Level150
    dw Level151
    dw Level152
    dw Level153
    dw Level154
    dw Level155
    dw Level156
    dw Level157
    dw Level158
    dw Level159
    dw Level15A
    dw Level15B
    dw Level15C
    dw Level15D
    dw Level15E
    dw Level15F
    dw Level160
    dw Level161
    dw Level162
    dw Level163
    dw Level164
    dw Level165
    dw Level166
    dw Level167
    dw Level168
    dw Level169
    dw Level16A
    dw Level16B
    dw Level16C
    dw Level16D
    dw Level16E
    dw Level16F
    dw Level170
    dw Level171
    dw Level172
    dw Level173
    dw Level174
    dw Level175
    dw Level176
    dw Level177
    dw Level178
    dw Level179
    dw Level17A
    dw Level17B
    dw Level17C
    dw Level17D
    dw Level17E
    dw Level17F
    dw Level180
    dw Level181
    dw Level182
    dw Level183
    dw Level184
    dw Level185
    dw Level186
    dw Level187
    dw Level188
    dw Level189
    dw Level18A
    dw Level18B
    dw Level18C
    dw Level18D
    dw Level18E
    dw Level18F
    dw Level190
    dw Level191
    dw Level192
    dw Level193
    dw Level194
    dw Level195
    dw Level196
    dw Level197
    dw Level198
    dw Level199
    dw Level19A
    dw Level19B
    dw Level19C
    dw Level19D
    dw Level19E
    dw Level19F
    dw Level1A0
    dw Level1A1
    dw Level1A2
    dw Level1A3
    dw Level1A4
    dw Level1A5
    dw Level1A6
    dw Level1A7
    dw Level1A8
    dw Level1A9
    dw Level1AA
    dw Level1AB
    dw Level1AC
    dw Level1AD
    dw Level1AE
    dw Level1AF
    dw Level1B0
    dw Level1B1
    dw Level1B2
    dw Level1B3
    dw Level1B4
    dw Level1B5
    dw Level1B6
    dw Level1B7
    dw Level1B8
    dw Level1B9
    dw Level1BA
    dw Level1BB
    dw Level1BC
    dw Level1BD
    dw Level1BE
    dw Level1BF
    dw Level1C0
    dw Level1C1
    dw Level1C2
    dw Level1C3
    dw Level1C4
    dw Level1C5
    dw Level1C6
    dw Level1C7
    dw Level1C8
    dw Level1C9
    dw Level1CA
    dw Level1CB
    dw Level1CC
    dw Level1CD
    dw Level1CE
    dw Level1CF
    dw Level1D0
    dw Level1D1
    dw Level1D2
    dw Level1D3
    dw Level1D4
    dw Level1D5
    dw Level1D6
    dw Level1D7
    dw Level1D8
    dw Level1D9
    dw Level1DA
    dw Level1DB
    dw Level1DC
    dw Level1DD
    dw Level1DE
    dw Level1DF
    dw Level1E0
    dw Level1E1
    dw Level1E2
    dw Level1E3
    dw Level1E4
    dw Level1E5
    dw Level1E6
    dw Level1E7
    dw Level1E8
    dw Level1E9
    dw Level1EA
    dw Level1EB
    dw Level1EC
    dw Level1ED
    dw Level1EE
    dw Level1EF
    dw Level1F0
    dw Level1F1
    dw Level1F2
    dw Level1F3
    dw Level1F4
    dw Level1F5
    dw Level1F6
    dw Level1F7
    dw Level1F8
    dw Level1F9
    dw Level1FA
    dw Level1FB
    dw Level1FC
    dw Level1FD
    dw Level1FE
    dw Level1FF

if !UberLevelNMI
    NMILevelResourcePointers:
        dw Level0NMI
        dw Level1NMI
        dw Level2NMI
        dw Level3NMI
        dw Level4NMI
        dw Level5NMI
        dw Level6NMI
        dw Level7NMI
        dw Level8NMI
        dw Level9NMI
        dw LevelANMI
        dw LevelBNMI
        dw LevelCNMI
        dw LevelDNMI
        dw LevelENMI
        dw LevelFNMI
        dw Level10NMI
        dw Level11NMI
        dw Level12NMI
        dw Level13NMI
        dw Level14NMI
        dw Level15NMI
        dw Level16NMI
        dw Level17NMI
        dw Level18NMI
        dw Level19NMI
        dw Level1ANMI
        dw Level1BNMI
        dw Level1CNMI
        dw Level1DNMI
        dw Level1ENMI
        dw Level1FNMI
        dw Level20NMI
        dw Level21NMI
        dw Level22NMI
        dw Level23NMI
        dw Level24NMI
        dw Level25NMI
        dw Level26NMI
        dw Level27NMI
        dw Level28NMI
        dw Level29NMI
        dw Level2ANMI
        dw Level2BNMI
        dw Level2CNMI
        dw Level2DNMI
        dw Level2ENMI
        dw Level2FNMI
        dw Level30NMI
        dw Level31NMI
        dw Level32NMI
        dw Level33NMI
        dw Level34NMI
        dw Level35NMI
        dw Level36NMI
        dw Level37NMI
        dw Level38NMI
        dw Level39NMI
        dw Level3ANMI
        dw Level3BNMI
        dw Level3CNMI
        dw Level3DNMI
        dw Level3ENMI
        dw Level3FNMI
        dw Level40NMI
        dw Level41NMI
        dw Level42NMI
        dw Level43NMI
        dw Level44NMI
        dw Level45NMI
        dw Level46NMI
        dw Level47NMI
        dw Level48NMI
        dw Level49NMI
        dw Level4ANMI
        dw Level4BNMI
        dw Level4CNMI
        dw Level4DNMI
        dw Level4ENMI
        dw Level4FNMI
        dw Level50NMI
        dw Level51NMI
        dw Level52NMI
        dw Level53NMI
        dw Level54NMI
        dw Level55NMI
        dw Level56NMI
        dw Level57NMI
        dw Level58NMI
        dw Level59NMI
        dw Level5ANMI
        dw Level5BNMI
        dw Level5CNMI
        dw Level5DNMI
        dw Level5ENMI
        dw Level5FNMI
        dw Level60NMI
        dw Level61NMI
        dw Level62NMI
        dw Level63NMI
        dw Level64NMI
        dw Level65NMI
        dw Level66NMI
        dw Level67NMI
        dw Level68NMI
        dw Level69NMI
        dw Level6ANMI
        dw Level6BNMI
        dw Level6CNMI
        dw Level6DNMI
        dw Level6ENMI
        dw Level6FNMI
        dw Level70NMI
        dw Level71NMI
        dw Level72NMI
        dw Level73NMI
        dw Level74NMI
        dw Level75NMI
        dw Level76NMI
        dw Level77NMI
        dw Level78NMI
        dw Level79NMI
        dw Level7ANMI
        dw Level7BNMI
        dw Level7CNMI
        dw Level7DNMI
        dw Level7ENMI
        dw Level7FNMI
        dw Level80NMI
        dw Level81NMI
        dw Level82NMI
        dw Level83NMI
        dw Level84NMI
        dw Level85NMI
        dw Level86NMI
        dw Level87NMI
        dw Level88NMI
        dw Level89NMI
        dw Level8ANMI
        dw Level8BNMI
        dw Level8CNMI
        dw Level8DNMI
        dw Level8ENMI
        dw Level8FNMI
        dw Level90NMI
        dw Level91NMI
        dw Level92NMI
        dw Level93NMI
        dw Level94NMI
        dw Level95NMI
        dw Level96NMI
        dw Level97NMI
        dw Level98NMI
        dw Level99NMI
        dw Level9ANMI
        dw Level9BNMI
        dw Level9CNMI
        dw Level9DNMI
        dw Level9ENMI
        dw Level9FNMI
        dw LevelA0NMI
        dw LevelA1NMI
        dw LevelA2NMI
        dw LevelA3NMI
        dw LevelA4NMI
        dw LevelA5NMI
        dw LevelA6NMI
        dw LevelA7NMI
        dw LevelA8NMI
        dw LevelA9NMI
        dw LevelAANMI
        dw LevelABNMI
        dw LevelACNMI
        dw LevelADNMI
        dw LevelAENMI
        dw LevelAFNMI
        dw LevelB0NMI
        dw LevelB1NMI
        dw LevelB2NMI
        dw LevelB3NMI
        dw LevelB4NMI
        dw LevelB5NMI
        dw LevelB6NMI
        dw LevelB7NMI
        dw LevelB8NMI
        dw LevelB9NMI
        dw LevelBANMI
        dw LevelBBNMI
        dw LevelBCNMI
        dw LevelBDNMI
        dw LevelBENMI
        dw LevelBFNMI
        dw LevelC0NMI
        dw LevelC1NMI
        dw LevelC2NMI
        dw LevelC3NMI
        dw LevelC4NMI
        dw LevelC5NMI
        dw LevelC6NMI
        dw LevelC7NMI
        dw LevelC8NMI
        dw LevelC9NMI
        dw LevelCANMI
        dw LevelCBNMI
        dw LevelCCNMI
        dw LevelCDNMI
        dw LevelCENMI
        dw LevelCFNMI
        dw LevelD0NMI
        dw LevelD1NMI
        dw LevelD2NMI
        dw LevelD3NMI
        dw LevelD4NMI
        dw LevelD5NMI
        dw LevelD6NMI
        dw LevelD7NMI
        dw LevelD8NMI
        dw LevelD9NMI
        dw LevelDANMI
        dw LevelDBNMI
        dw LevelDCNMI
        dw LevelDDNMI
        dw LevelDENMI
        dw LevelDFNMI
        dw LevelE0NMI
        dw LevelE1NMI
        dw LevelE2NMI
        dw LevelE3NMI
        dw LevelE4NMI
        dw LevelE5NMI
        dw LevelE6NMI
        dw LevelE7NMI
        dw LevelE8NMI
        dw LevelE9NMI
        dw LevelEANMI
        dw LevelEBNMI
        dw LevelECNMI
        dw LevelEDNMI
        dw LevelEENMI
        dw LevelEFNMI
        dw LevelF0NMI
        dw LevelF1NMI
        dw LevelF2NMI
        dw LevelF3NMI
        dw LevelF4NMI
        dw LevelF5NMI
        dw LevelF6NMI
        dw LevelF7NMI
        dw LevelF8NMI
        dw LevelF9NMI
        dw LevelFANMI
        dw LevelFBNMI
        dw LevelFCNMI
        dw LevelFDNMI
        dw LevelFENMI
        dw LevelFFNMI
        dw Level100NMI
        dw Level101NMI
        dw Level102NMI
        dw Level103NMI
        dw Level104NMI
        dw Level105NMI
        dw Level106NMI
        dw Level107NMI
        dw Level108NMI
        dw Level109NMI
        dw Level10ANMI
        dw Level10BNMI
        dw Level10CNMI
        dw Level10DNMI
        dw Level10ENMI
        dw Level10FNMI
        dw Level110NMI
        dw Level111NMI
        dw Level112NMI
        dw Level113NMI
        dw Level114NMI
        dw Level115NMI
        dw Level116NMI
        dw Level117NMI
        dw Level118NMI
        dw Level119NMI
        dw Level11ANMI
        dw Level11BNMI
        dw Level11CNMI
        dw Level11DNMI
        dw Level11ENMI
        dw Level11FNMI
        dw Level120NMI
        dw Level121NMI
        dw Level122NMI
        dw Level123NMI
        dw Level124NMI
        dw Level125NMI
        dw Level126NMI
        dw Level127NMI
        dw Level128NMI
        dw Level129NMI
        dw Level12ANMI
        dw Level12BNMI
        dw Level12CNMI
        dw Level12DNMI
        dw Level12ENMI
        dw Level12FNMI
        dw Level130NMI
        dw Level131NMI
        dw Level132NMI
        dw Level133NMI
        dw Level134NMI
        dw Level135NMI
        dw Level136NMI
        dw Level137NMI
        dw Level138NMI
        dw Level139NMI
        dw Level13ANMI
        dw Level13BNMI
        dw Level13CNMI
        dw Level13DNMI
        dw Level13ENMI
        dw Level13FNMI
        dw Level140NMI
        dw Level141NMI
        dw Level142NMI
        dw Level143NMI
        dw Level144NMI
        dw Level145NMI
        dw Level146NMI
        dw Level147NMI
        dw Level148NMI
        dw Level149NMI
        dw Level14ANMI
        dw Level14BNMI
        dw Level14CNMI
        dw Level14DNMI
        dw Level14ENMI
        dw Level14FNMI
        dw Level150NMI
        dw Level151NMI
        dw Level152NMI
        dw Level153NMI
        dw Level154NMI
        dw Level155NMI
        dw Level156NMI
        dw Level157NMI
        dw Level158NMI
        dw Level159NMI
        dw Level15ANMI
        dw Level15BNMI
        dw Level15CNMI
        dw Level15DNMI
        dw Level15ENMI
        dw Level15FNMI
        dw Level160NMI
        dw Level161NMI
        dw Level162NMI
        dw Level163NMI
        dw Level164NMI
        dw Level165NMI
        dw Level166NMI
        dw Level167NMI
        dw Level168NMI
        dw Level169NMI
        dw Level16ANMI
        dw Level16BNMI
        dw Level16CNMI
        dw Level16DNMI
        dw Level16ENMI
        dw Level16FNMI
        dw Level170NMI
        dw Level171NMI
        dw Level172NMI
        dw Level173NMI
        dw Level174NMI
        dw Level175NMI
        dw Level176NMI
        dw Level177NMI
        dw Level178NMI
        dw Level179NMI
        dw Level17ANMI
        dw Level17BNMI
        dw Level17CNMI
        dw Level17DNMI
        dw Level17ENMI
        dw Level17FNMI
        dw Level180NMI
        dw Level181NMI
        dw Level182NMI
        dw Level183NMI
        dw Level184NMI
        dw Level185NMI
        dw Level186NMI
        dw Level187NMI
        dw Level188NMI
        dw Level189NMI
        dw Level18ANMI
        dw Level18BNMI
        dw Level18CNMI
        dw Level18DNMI
        dw Level18ENMI
        dw Level18FNMI
        dw Level190NMI
        dw Level191NMI
        dw Level192NMI
        dw Level193NMI
        dw Level194NMI
        dw Level195NMI
        dw Level196NMI
        dw Level197NMI
        dw Level198NMI
        dw Level199NMI
        dw Level19ANMI
        dw Level19BNMI
        dw Level19CNMI
        dw Level19DNMI
        dw Level19ENMI
        dw Level19FNMI
        dw Level1A0NMI
        dw Level1A1NMI
        dw Level1A2NMI
        dw Level1A3NMI
        dw Level1A4NMI
        dw Level1A5NMI
        dw Level1A6NMI
        dw Level1A7NMI
        dw Level1A8NMI
        dw Level1A9NMI
        dw Level1AANMI
        dw Level1ABNMI
        dw Level1ACNMI
        dw Level1ADNMI
        dw Level1AENMI
        dw Level1AFNMI
        dw Level1B0NMI
        dw Level1B1NMI
        dw Level1B2NMI
        dw Level1B3NMI
        dw Level1B4NMI
        dw Level1B5NMI
        dw Level1B6NMI
        dw Level1B7NMI
        dw Level1B8NMI
        dw Level1B9NMI
        dw Level1BANMI
        dw Level1BBNMI
        dw Level1BCNMI
        dw Level1BDNMI
        dw Level1BENMI
        dw Level1BFNMI
        dw Level1C0NMI
        dw Level1C1NMI
        dw Level1C2NMI
        dw Level1C3NMI
        dw Level1C4NMI
        dw Level1C5NMI
        dw Level1C6NMI
        dw Level1C7NMI
        dw Level1C8NMI
        dw Level1C9NMI
        dw Level1CANMI
        dw Level1CBNMI
        dw Level1CCNMI
        dw Level1CDNMI
        dw Level1CENMI
        dw Level1CFNMI
        dw Level1D0NMI
        dw Level1D1NMI
        dw Level1D2NMI
        dw Level1D3NMI
        dw Level1D4NMI
        dw Level1D5NMI
        dw Level1D6NMI
        dw Level1D7NMI
        dw Level1D8NMI
        dw Level1D9NMI
        dw Level1DANMI
        dw Level1DBNMI
        dw Level1DCNMI
        dw Level1DDNMI
        dw Level1DENMI
        dw Level1DFNMI
        dw Level1E0NMI
        dw Level1E1NMI
        dw Level1E2NMI
        dw Level1E3NMI
        dw Level1E4NMI
        dw Level1E5NMI
        dw Level1E6NMI
        dw Level1E7NMI
        dw Level1E8NMI
        dw Level1E9NMI
        dw Level1EANMI
        dw Level1EBNMI
        dw Level1ECNMI
        dw Level1EDNMI
        dw Level1EENMI
        dw Level1EFNMI
        dw Level1F0NMI
        dw Level1F1NMI
        dw Level1F2NMI
        dw Level1F3NMI
        dw Level1F4NMI
        dw Level1F5NMI
        dw Level1F6NMI
        dw Level1F7NMI
        dw Level1F8NMI
        dw Level1F9NMI
        dw Level1FANMI
        dw Level1FBNMI
        dw Level1FCNMI
        dw Level1FDNMI
        dw Level1FENMI
        dw Level1FFNMI
endif

GamemodeResourcePointers:
    dw Gamemode0
    dw Gamemode1
    dw Gamemode2
    dw Gamemode3
    dw Gamemode4
    dw Gamemode5
    dw Gamemode6
    dw Gamemode7
    dw Gamemode8
    dw Gamemode9
    dw GamemodeA
    dw GamemodeB
    dw GamemodeC
    dw GamemodeD
    dw GamemodeE
    dw GamemodeF
    dw Gamemode10
    dw Gamemode11
    dw Gamemode12
    dw Gamemode13
    dw Gamemode14
    dw Gamemode15
    dw Gamemode16
    dw Gamemode17
    dw Gamemode18
    dw Gamemode19
    dw Gamemode1A
    dw Gamemode1B
    dw Gamemode1C
    dw Gamemode1D
    dw Gamemode1E
    dw Gamemode1F
    dw Gamemode20
    dw Gamemode21
    dw Gamemode22
    dw Gamemode23
    dw Gamemode24
    dw Gamemode25
    dw Gamemode26
    dw Gamemode27
    dw Gamemode28
    dw Gamemode29
    dw Gamemode2A
    dw Gamemode2B
    dw Gamemode2C
    dw Gamemode2D
    dw Gamemode2E
    dw Gamemode2F
    dw Gamemode30
    dw Gamemode31
    dw Gamemode32
    dw Gamemode33
    dw Gamemode34
    dw Gamemode35
    dw Gamemode36
    dw Gamemode37
    dw Gamemode38
    dw Gamemode39
    dw Gamemode3A
    dw Gamemode3B
    dw Gamemode3C
    dw Gamemode3D
    dw Gamemode3E
    dw Gamemode3F
    dw Gamemode40
    dw Gamemode41
    dw Gamemode42
    dw Gamemode43
    dw Gamemode44
    dw Gamemode45
    dw Gamemode46
    dw Gamemode47
    dw Gamemode48
    dw Gamemode49
    dw Gamemode4A
    dw Gamemode4B
    dw Gamemode4C
    dw Gamemode4D
    dw Gamemode4E
    dw Gamemode4F
    dw Gamemode50
    dw Gamemode51
    dw Gamemode52
    dw Gamemode53
    dw Gamemode54
    dw Gamemode55
    dw Gamemode56
    dw Gamemode57
    dw Gamemode58
    dw Gamemode59
    dw Gamemode5A
    dw Gamemode5B
    dw Gamemode5C
    dw Gamemode5D
    dw Gamemode5E
    dw Gamemode5F
    dw Gamemode60
    dw Gamemode61
    dw Gamemode62
    dw Gamemode63
    dw Gamemode64
    dw Gamemode65
    dw Gamemode66
    dw Gamemode67
    dw Gamemode68
    dw Gamemode69
    dw Gamemode6A
    dw Gamemode6B
    dw Gamemode6C
    dw Gamemode6D
    dw Gamemode6E
    dw Gamemode6F
    dw Gamemode70
    dw Gamemode71
    dw Gamemode72
    dw Gamemode73
    dw Gamemode74
    dw Gamemode75
    dw Gamemode76
    dw Gamemode77
    dw Gamemode78
    dw Gamemode79
    dw Gamemode7A
    dw Gamemode7B
    dw Gamemode7C
    dw Gamemode7D
    dw Gamemode7E
    dw Gamemode7F
    dw Gamemode80
    dw Gamemode81
    dw Gamemode82
    dw Gamemode83
    dw Gamemode84
    dw Gamemode85
    dw Gamemode86
    dw Gamemode87
    dw Gamemode88
    dw Gamemode89
    dw Gamemode8A
    dw Gamemode8B
    dw Gamemode8C
    dw Gamemode8D
    dw Gamemode8E
    dw Gamemode8F
    dw Gamemode90
    dw Gamemode91
    dw Gamemode92
    dw Gamemode93
    dw Gamemode94
    dw Gamemode95
    dw Gamemode96
    dw Gamemode97
    dw Gamemode98
    dw Gamemode99
    dw Gamemode9A
    dw Gamemode9B
    dw Gamemode9C
    dw Gamemode9D
    dw Gamemode9E
    dw Gamemode9F
    dw GamemodeA0
    dw GamemodeA1
    dw GamemodeA2
    dw GamemodeA3
    dw GamemodeA4
    dw GamemodeA5
    dw GamemodeA6
    dw GamemodeA7
    dw GamemodeA8
    dw GamemodeA9
    dw GamemodeAA
    dw GamemodeAB
    dw GamemodeAC
    dw GamemodeAD
    dw GamemodeAE
    dw GamemodeAF
    dw GamemodeB0
    dw GamemodeB1
    dw GamemodeB2
    dw GamemodeB3
    dw GamemodeB4
    dw GamemodeB5
    dw GamemodeB6
    dw GamemodeB7
    dw GamemodeB8
    dw GamemodeB9
    dw GamemodeBA
    dw GamemodeBB
    dw GamemodeBC
    dw GamemodeBD
    dw GamemodeBE
    dw GamemodeBF
    dw GamemodeC0
    dw GamemodeC1
    dw GamemodeC2
    dw GamemodeC3
    dw GamemodeC4
    dw GamemodeC5
    dw GamemodeC6
    dw GamemodeC7
    dw GamemodeC8
    dw GamemodeC9
    dw GamemodeCA
    dw GamemodeCB
    dw GamemodeCC
    dw GamemodeCD
    dw GamemodeCE
    dw GamemodeCF
    dw GamemodeD0
    dw GamemodeD1
    dw GamemodeD2
    dw GamemodeD3
    dw GamemodeD4
    dw GamemodeD5
    dw GamemodeD6
    dw GamemodeD7
    dw GamemodeD8
    dw GamemodeD9
    dw GamemodeDA
    dw GamemodeDB
    dw GamemodeDC
    dw GamemodeDD
    dw GamemodeDE
    dw GamemodeDF
    dw GamemodeE0
    dw GamemodeE1
    dw GamemodeE2
    dw GamemodeE3
    dw GamemodeE4
    dw GamemodeE5
    dw GamemodeE6
    dw GamemodeE7
    dw GamemodeE8
    dw GamemodeE9
    dw GamemodeEA
    dw GamemodeEB
    dw GamemodeEC
    dw GamemodeED
    dw GamemodeEE
    dw GamemodeEF
    dw GamemodeF0
    dw GamemodeF1
    dw GamemodeF2
    dw GamemodeF3
    dw GamemodeF4
    dw GamemodeF5
    dw GamemodeF6
    dw GamemodeF7
    dw GamemodeF8
    dw GamemodeF9
    dw GamemodeFA
    dw GamemodeFB
    dw GamemodeFC
    dw GamemodeFD
    dw GamemodeFE
    dw GamemodeFF


if !UberGamemodeNMI
    NMIGamemodeResourcePointers:
        dw Gamemode0NMI
        dw Gamemode1NMI
        dw Gamemode2NMI
        dw Gamemode3NMI
        dw Gamemode4NMI
        dw Gamemode5NMI
        dw Gamemode6NMI
        dw Gamemode7NMI
        dw Gamemode8NMI
        dw Gamemode9NMI
        dw GamemodeANMI
        dw GamemodeBNMI
        dw GamemodeCNMI
        dw GamemodeDNMI
        dw GamemodeENMI
        dw GamemodeFNMI
        dw Gamemode10NMI
        dw Gamemode11NMI
        dw Gamemode12NMI
        dw Gamemode13NMI
        dw Gamemode14NMI
        dw Gamemode15NMI
        dw Gamemode16NMI
        dw Gamemode17NMI
        dw Gamemode18NMI
        dw Gamemode19NMI
        dw Gamemode1ANMI
        dw Gamemode1BNMI
        dw Gamemode1CNMI
        dw Gamemode1DNMI
        dw Gamemode1ENMI
        dw Gamemode1FNMI
        dw Gamemode20NMI
        dw Gamemode21NMI
        dw Gamemode22NMI
        dw Gamemode23NMI
        dw Gamemode24NMI
        dw Gamemode25NMI
        dw Gamemode26NMI
        dw Gamemode27NMI
        dw Gamemode28NMI
        dw Gamemode29NMI
        dw Gamemode2ANMI
        dw Gamemode2BNMI
        dw Gamemode2CNMI
        dw Gamemode2DNMI
        dw Gamemode2ENMI
        dw Gamemode2FNMI
        dw Gamemode30NMI
        dw Gamemode31NMI
        dw Gamemode32NMI
        dw Gamemode33NMI
        dw Gamemode34NMI
        dw Gamemode35NMI
        dw Gamemode36NMI
        dw Gamemode37NMI
        dw Gamemode38NMI
        dw Gamemode39NMI
        dw Gamemode3ANMI
        dw Gamemode3BNMI
        dw Gamemode3CNMI
        dw Gamemode3DNMI
        dw Gamemode3ENMI
        dw Gamemode3FNMI
        dw Gamemode40NMI
        dw Gamemode41NMI
        dw Gamemode42NMI
        dw Gamemode43NMI
        dw Gamemode44NMI
        dw Gamemode45NMI
        dw Gamemode46NMI
        dw Gamemode47NMI
        dw Gamemode48NMI
        dw Gamemode49NMI
        dw Gamemode4ANMI
        dw Gamemode4BNMI
        dw Gamemode4CNMI
        dw Gamemode4DNMI
        dw Gamemode4ENMI
        dw Gamemode4FNMI
        dw Gamemode50NMI
        dw Gamemode51NMI
        dw Gamemode52NMI
        dw Gamemode53NMI
        dw Gamemode54NMI
        dw Gamemode55NMI
        dw Gamemode56NMI
        dw Gamemode57NMI
        dw Gamemode58NMI
        dw Gamemode59NMI
        dw Gamemode5ANMI
        dw Gamemode5BNMI
        dw Gamemode5CNMI
        dw Gamemode5DNMI
        dw Gamemode5ENMI
        dw Gamemode5FNMI
        dw Gamemode60NMI
        dw Gamemode61NMI
        dw Gamemode62NMI
        dw Gamemode63NMI
        dw Gamemode64NMI
        dw Gamemode65NMI
        dw Gamemode66NMI
        dw Gamemode67NMI
        dw Gamemode68NMI
        dw Gamemode69NMI
        dw Gamemode6ANMI
        dw Gamemode6BNMI
        dw Gamemode6CNMI
        dw Gamemode6DNMI
        dw Gamemode6ENMI
        dw Gamemode6FNMI
        dw Gamemode70NMI
        dw Gamemode71NMI
        dw Gamemode72NMI
        dw Gamemode73NMI
        dw Gamemode74NMI
        dw Gamemode75NMI
        dw Gamemode76NMI
        dw Gamemode77NMI
        dw Gamemode78NMI
        dw Gamemode79NMI
        dw Gamemode7ANMI
        dw Gamemode7BNMI
        dw Gamemode7CNMI
        dw Gamemode7DNMI
        dw Gamemode7ENMI
        dw Gamemode7FNMI
        dw Gamemode80NMI
        dw Gamemode81NMI
        dw Gamemode82NMI
        dw Gamemode83NMI
        dw Gamemode84NMI
        dw Gamemode85NMI
        dw Gamemode86NMI
        dw Gamemode87NMI
        dw Gamemode88NMI
        dw Gamemode89NMI
        dw Gamemode8ANMI
        dw Gamemode8BNMI
        dw Gamemode8CNMI
        dw Gamemode8DNMI
        dw Gamemode8ENMI
        dw Gamemode8FNMI
        dw Gamemode90NMI
        dw Gamemode91NMI
        dw Gamemode92NMI
        dw Gamemode93NMI
        dw Gamemode94NMI
        dw Gamemode95NMI
        dw Gamemode96NMI
        dw Gamemode97NMI
        dw Gamemode98NMI
        dw Gamemode99NMI
        dw Gamemode9ANMI
        dw Gamemode9BNMI
        dw Gamemode9CNMI
        dw Gamemode9DNMI
        dw Gamemode9ENMI
        dw Gamemode9FNMI
        dw GamemodeA0NMI
        dw GamemodeA1NMI
        dw GamemodeA2NMI
        dw GamemodeA3NMI
        dw GamemodeA4NMI
        dw GamemodeA5NMI
        dw GamemodeA6NMI
        dw GamemodeA7NMI
        dw GamemodeA8NMI
        dw GamemodeA9NMI
        dw GamemodeAANMI
        dw GamemodeABNMI
        dw GamemodeACNMI
        dw GamemodeADNMI
        dw GamemodeAENMI
        dw GamemodeAFNMI
        dw GamemodeB0NMI
        dw GamemodeB1NMI
        dw GamemodeB2NMI
        dw GamemodeB3NMI
        dw GamemodeB4NMI
        dw GamemodeB5NMI
        dw GamemodeB6NMI
        dw GamemodeB7NMI
        dw GamemodeB8NMI
        dw GamemodeB9NMI
        dw GamemodeBANMI
        dw GamemodeBBNMI
        dw GamemodeBCNMI
        dw GamemodeBDNMI
        dw GamemodeBENMI
        dw GamemodeBFNMI
        dw GamemodeC0NMI
        dw GamemodeC1NMI
        dw GamemodeC2NMI
        dw GamemodeC3NMI
        dw GamemodeC4NMI
        dw GamemodeC5NMI
        dw GamemodeC6NMI
        dw GamemodeC7NMI
        dw GamemodeC8NMI
        dw GamemodeC9NMI
        dw GamemodeCANMI
        dw GamemodeCBNMI
        dw GamemodeCCNMI
        dw GamemodeCDNMI
        dw GamemodeCENMI
        dw GamemodeCFNMI
        dw GamemodeD0NMI
        dw GamemodeD1NMI
        dw GamemodeD2NMI
        dw GamemodeD3NMI
        dw GamemodeD4NMI
        dw GamemodeD5NMI
        dw GamemodeD6NMI
        dw GamemodeD7NMI
        dw GamemodeD8NMI
        dw GamemodeD9NMI
        dw GamemodeDANMI
        dw GamemodeDBNMI
        dw GamemodeDCNMI
        dw GamemodeDDNMI
        dw GamemodeDENMI
        dw GamemodeDFNMI
        dw GamemodeE0NMI
        dw GamemodeE1NMI
        dw GamemodeE2NMI
        dw GamemodeE3NMI
        dw GamemodeE4NMI
        dw GamemodeE5NMI
        dw GamemodeE6NMI
        dw GamemodeE7NMI
        dw GamemodeE8NMI
        dw GamemodeE9NMI
        dw GamemodeEANMI
        dw GamemodeEBNMI
        dw GamemodeECNMI
        dw GamemodeEDNMI
        dw GamemodeEENMI
        dw GamemodeEFNMI
        dw GamemodeF0NMI
        dw GamemodeF1NMI
        dw GamemodeF2NMI
        dw GamemodeF3NMI
        dw GamemodeF4NMI
        dw GamemodeF5NMI
        dw GamemodeF6NMI
        dw GamemodeF7NMI
        dw GamemodeF8NMI
        dw GamemodeF9NMI
        dw GamemodeFANMI
        dw GamemodeFBNMI
        dw GamemodeFCNMI
        dw GamemodeFDNMI
        dw GamemodeFENMI
        dw GamemodeFFNMI
endif


OverworldResourcePointers:
    dw Overworld0
    dw Overworld1
    dw Overworld2
    dw Overworld3
    dw Overworld4
    dw Overworld5
    dw Overworld6


if !UberOverworldNMI
    NMIOverworldResourcePointers:
        dw Overworld0NMI
        dw Overworld1NMI
        dw Overworld2NMI
        dw Overworld3NMI
        dw Overworld4NMI
        dw Overworld5NMI
        dw Overworld6NMI
endif

